In [ ]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [ ]:
df = pd.read_csv('/content/IMDB Dataset.csv', engine='python', escapechar='\\', on_bad_lines='skip')

In [ ]:
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
8678  In Strangers On A Train, it's obvious from the...  positive
8679  The BBC'S Blue Planet is simply jaw-dropping. ...  positive
8680  I mistakenly kept myself awake late last night...  negative
8681  Its my favourite film because there's so much ...  positive
8682  As long as you go into this movie knowing that...  positive

[8683 rows x 2 columns]

In [ ]:
df['review'][10].lower()

'phil the alien is one of those quirky films where the humour is based around the oddness of everything rather than actual punchlines.<br /><br />at first it was very odd and pretty funny but as the movie progressed i didn\'t find the jokes or oddness funny anymore.<br /><br />its a low budget film (thats never a problem in itself), there were some pretty interesting characters, but eventually i just lost interest.<br /><br />i imagine this film would appeal to a stoner who is currently partaking.<br /><br />for something similar but better try "brother from another planet"'

In [ ]:
df['review'] = df['review'].str.lower() #lower case

In [ ]:
df

                                                 review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. <br /><br />the...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
8678  in strangers on a train, it's obvious from the...  positive
8679  the bbc's blue planet is simply jaw-dropping. ...  positive
8680  i mistakenly kept myself awake late last night...  negative
8681  its my favourite film because there's so much ...  positive
8682  as long as you go into this movie knowing that...  positive

[8683 rows x 2 columns]

In [ ]:
#remove html tags

In [ ]:
text = """
<p>This is a <b>great</b> movie!</p>
<br />
<div>I <i>really</i> enjoyed the <a href="#">storyline</a>.</div>
"""

In [ ]:
clean_text = BeautifulSoup(text, "html.parser").get_text()          #handle complex structure
print(clean_text)

This is a great movie!

I really enjoyed the storyline.

In [ ]:
text2 = """
<p>This is a <b>great</b> movie!</p>
<br />
<div>I <i>really</i> enjoyed the <a href="#">storyline</a>.</div>
"""

In [ ]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    text = pattern.sub('', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [ ]:
remove_html_tags(text2)

'This is a great movie! I really enjoyed the storyline.'

In [ ]:
# URLS

In [ ]:
text1 = "Visit my portfolio at https://www.mywebsite.com/projects/data-science"
text2 = "Check this blog http://medium.com/@user123/machine-learning-basics"
text3 = "Search anything on www.bing.com for quick results"
text4 = "Download dataset from https://github.com/user/repo/data.csv"
text5 = "Apply for jobs at https://www.linkedin.com/jobs/data-analyst"

In [ ]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

In [ ]:
remove_url(text2)

'Check this blog '

In [ ]:
#Punctuation marks

In [ ]:
import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude = string.punctuation

In [ ]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [ ]:
text = 'hello! i hope you are doing well. Can you please close that door?'

In [ ]:
remove_punc(text)

'hello i hope you are doing well Can you please close that door'

In [ ]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [ ]:
remove_punc1(text)

'hello i hope you are doing well Can you please close that door'

In [ ]:
# Chat word Treatment

In [ ]:
slang_dict = {
    "A3": "Anytime Anywhere Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ASL": "Age Sex Location",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Cant Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What Its Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "IDC": "I Dont Care",
    "IDK": "I Dont Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My Ass Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "PITA": "Pain In The Ass",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My Ass Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "STATS": "Your Sex And Age",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long Didnt Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta Ta For Now",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours Forever",
    "W": "Win",
    "W8": "Wait",
    "WB": "Welcome Back",
    "WTF": "What The F",
    "WTG": "Way To Go",
    "WUF": "Where Are You From",
    "WYD": "What You Doing",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping Bored Tired"
}

In [ ]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in slang_dict:
            new_text.append(slang_dict[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [ ]:
text = 'WB call me anytime and TBH u are the best'

In [ ]:
chat_conversion(text)

'Welcome Back call me anytime and To Be Honest You are the best'

In [ ]:
# spell checker

In [ ]:
from textblob import TextBlob

In [ ]:
text= 'hiiiii , whaat you ar doing . lets makei some nooodls'

In [ ]:
textBlb = TextBlob(text)
textBlb.correct().string

'hiiiii , what you ar doing . lets make some nooodls'

In [ ]:
!pip install pyspellchecker

Collecting pyspellchecker
  Downloading pyspellchecker-0.9.0-py3-none-any.whl.metadata (9.3 kB)
Downloading pyspellchecker-0.9.0-py3-none-any.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 68.0 MB/s eta 0:00:00
Installing collected packages: pyspellchecker
Successfully installed pyspellchecker-0.9.0

In [ ]:
from spellchecker import SpellChecker

spell = SpellChecker()
corrected = " ".join([spell.correction(word) or word for word in text.split()])

print(corrected)

hiiiii , what you ar doing . lets make some noodles

In [ ]:
# Removing Stop Words

In [ ]:
import nltk
from nltk.corpus import stopwords

In [ ]:

nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
stop_words = set(stopwords.words('english'))

def remove_stopwords1(text):
    new_text = []

    for word in text.split():
        if word.lower() not in stop_words:
            new_text.append(word)

    return " ".join(new_text)

In [ ]:
def remove_stopwords(text):
    return " ".join([word for word in text.split() if word.lower() not in stop_words])

In [ ]:
text = "This is a very simple example to demonstrate how we remove stopwords from a sentence"

In [ ]:
remove_stopwords1(text)

'simple example demonstrate remove stopwords sentence'

In [ ]:
remove_stopwords(text)

'simple example demonstrate remove stopwords sentence'

In [ ]:
# Emoji preprocessing

In [ ]:
text = "I love this movie 😍🔥 but the ending was sad 😢💔"

In [ ]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map
        u"\U0001F1E0-\U0001F1FF"  # flags
        "]+", flags=re.UNICODE)

    return emoji_pattern.sub(r'', text)

In [ ]:
print(remove_emoji(text))

I love this movie  but the ending was sad

In [ ]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 13.0 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [ ]:
import emoji

def replace_emoji(text):
    return emoji.demojize(text)

In [ ]:
#Tokenization

In [ ]:
text ="""Hello! I'm learning NLP. Tokenization is fun, isn't it? 😊"""

In [ ]:
sent1 = "I have a Ph.D in A.I"
sent2 = "We're here to help! mail us at nks@gmail.com"
sent3 = "A 5km ride cost $10.50"

In [ ]:
tokens = text.split()
print(tokens)

['Hello!', "I'm", 'learning', 'NLP.', 'Tokenization', 'is', 'fun,', "isn't", 'it?', '😊']

In [ ]:
tokens = sent1.split()
print(tokens)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [ ]:
tokens = sent2.split()
print(tokens)

["We're", 'here', 'to', 'help!', 'mail', 'us', 'at', 'nks@gmail.com']

In [ ]:
tokens = sent3.split()
print(tokens)

['A', '5km', 'ride', 'cost', '$10.50']

In [ ]:
import nltk
nltk.download('punkt_tab') # Download punkt_tab as suggested by the error
nltk.download('punkt') # Keep original download as well, if needed

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize

tokens = word_tokenize(text)
print(tokens)

['Hello', '!', 'I', "'m", 'learning', 'NLP', '.', 'Tokenization', 'is', 'fun', ',', 'is', "n't", 'it', '?', '😊']

In [ ]:
tokens = word_tokenize(sent1)
print(tokens)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [ ]:
tokens = word_tokenize(sent2)
print(tokens)

['We', "'re", 'here', 'to', 'help', '!', 'mail', 'us', 'at', 'nks', '@', 'gmail.com']

In [ ]:
tokens = word_tokenize(sent3)
print(tokens)

['A', '5km', 'ride', 'cost', '$', '10.50']

In [ ]:
from nltk.tokenize import sent_tokenize

sentences = sent_tokenize(text)
print(sentences)

['Hello!', "I'm learning NLP.", "Tokenization is fun, isn't it?", '😊']

In [ ]:
tokens = sent_tokenize(sent1)
print(tokens)

['I have a Ph.D in A.I']

In [ ]:
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')
tokens = tokenizer.tokenize(text)
print(tokens)

['Hello', 'I', 'm', 'learning', 'NLP', 'Tokenization', 'is', 'fun', 'isn', 't', 'it']

In [ ]:
from nltk.tokenize import WhitespaceTokenizer

tokens = WhitespaceTokenizer().tokenize(text)
print(tokens)

['Hello!', "I'm", 'learning', 'NLP.', 'Tokenization', 'is', 'fun,', "isn't", 'it?', '😊']

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(text)

tokens = [token.text for token in doc]
print(tokens)

['Hello', '!', 'I', "'m", 'learning', 'NLP', '.', 'Tokenization', 'is', 'fun', ',', 'is', "n't", 'it', '?', '😊']

In [ ]:
doc = nlp(sent1)

tokens = [token.text for token in doc]
print(tokens)

['I', 'have', 'a', 'Ph', '.', 'D', 'in', 'A.I']

In [ ]:
doc = nlp(sent2)

tokens = [token.text for token in doc]
print(tokens)

['We', "'re", 'here', 'to', 'help', '!', 'mail', 'us', 'at', 'nks@gmail.com']

In [ ]:
doc = nlp(sent3)

tokens = [token.text for token in doc]
print(tokens)

['A', '5', 'km', 'ride', 'cost', '$', '10.50']

In [ ]:
# Stemming

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
text = "walk walks walking walked"
print(stem_words(text))

walk walk walk walk

In [ ]:
text = "probably my alltime favorite movie a story of selflessness sacrifice and dedication"
print(stem_words(text))

probabl my alltim favorit movi a stori of selfless sacrific and dedic

In [ ]:
# Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [ ]:

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
print( lemmatize_words(text))

probably my alltime favorite movie a story of selflessness sacrifice and dedication

In [ ]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [ ]:
# Step 1: Imports
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag, word_tokenize

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')


lemmatizer = WordNetLemmatizer()

#convert NLTK POS → WordNet POS
def get_wordnet_pos(tag):
    if tag.startswith('J'):   # Adjective
        return wordnet.ADJ
    elif tag.startswith('V'): # Verb
        return wordnet.VERB
    elif tag.startswith('N'): # Noun
        return wordnet.NOUN
    elif tag.startswith('R'): # Adverb
        return wordnet.ADV
    else:
        return wordnet.NOUN   # Default

def advanced_lemmatization(text):
    # Tokenize
    words = word_tokenize(text)

    # POS tagging
    tagged_words = pos_tag(words)

    # Lemmatize with POS
    lemmatized_words = [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged_words
    ]

    return " ".join(lemmatized_words)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
advanced_lemmatization(text)

'probably my alltime favorite movie a story of selflessness sacrifice and dedication'